=== twvwrigth/40270/XML/gramatica.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT autos (auto*)>
<!ELEMENT auto (marca, modelo, año)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT año (#PCDATA)>

=== twvwrigth/40270/XML/gramatica.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE autos SYSTEM "gramatica.dtd">
<autos>
    <auto>
        <marca>Toyota</marca>
        <modelo>Corolla</modelo>        
        <año>2020</año>
    </auto>
    <auto>
        <marca>Honda</marca>
        <modelo>Civic</modelo>
        <año>2019</año>
    </auto>
</autos>
